### ISSUE TITLE
[에러] 대화창(지나간대화)

### ISSUE THREAD

**Issue by JOOHYUN85** [mossland/mossverse#14]
대화가 지나간 윗부분 내용이 스크롤해도 보이지 않음
처음 입장시에는 아예 빈칸으로 보임

https://github.com/mossland/mossverse/assets/128334516/36cc71da-6031-4368-81fb-f36d305bc891

**Comment by JOOHYUN85** [comment]
넵 확인했습니다. 감사합니다. 혹시 스크롤 기능은 못들어가나요?

https://github.com/mossland/mossverse/assets/128334516/9dd54923-4a3a-45fe-b715-66b6ee856384

**Comment by yadorann** [comment]
제 주관적 의견이긴 한데 스크롤이 없는 게 좀 더 이쁜 것 같아서 안보이는 스크롤로 적용했습니다 안그러면 계속 고정으로 스크롤이 떠 있어서 좀 이상해 보이더라구요

**Comment by JOOHYUN85** [comment]
아하 넵 알겠습니다~!
