### ISSUE TITLE
투표 오픈시간 관련

### ISSUE THREAD

**Issue by JOOHYUN85** [mossland/mossverse#27]
투표시작일이 오늘부터인데 투표 오픈이 되지 않았다고 투표가 되지않습니다. 
최근까지도 시작일에 투표 가능했었는데 오늘 눌러보니 빨간색으로 안된다는 메시지가 뜨네요

오늘 7/6일이고 7/6일시작되는 요 2개가 안됩니당

![image](https://github.com/mossland/mossverse/assets/128334516/3d2be1e4-6679-49c7-b9e2-dd199d1f51b3)

**Comment by yadorann** [comment]
아마 시간이 아직 오픈 전인 것 같습니다 일단 오픈하기 전까진 active, 비활성화상태로 보이게끔 처리해놧습니다

**Comment by JOOHYUN85** [comment]
넵 확인했습니다 감사합니다
