### ISSUE TITLE
[급] 투표소 안건내용 안보임/ 투표생성 안됨

### ISSUE THREAD

**Issue by JOOHYUN85** [mossland/mossverse#31]
1. 투표창에서 안건을 누르면 위에 빨간 메시지가 뜨고 오른쪽에 내용이 안나옴
2. 내용을 쓰고 CREATE를 누르면 위에 빨간 메시지가 뜨고 생성이 안됨

메시지창 내용 **[Fragment "mocOwnershipFragment" is never used.]**

![image](https://github.com/mossland/mossverse/assets/128334516/e45a7e46-4416-4f3b-bc9d-3f281a466724)

![image](https://github.com/mossland/mossverse/assets/128334516/7b8f7b2b-604b-417b-9573-f29497eb51f2)

**Comment by yadorann** [comment]
수정 후 반영했습니다

**Comment by JOOHYUN85** [comment]
감사합니다!
