### ISSUE TITLE
투표소 ANSWERS 글자수

### ISSUE THREAD

**Issue by JOOHYUN85** [mossland/mossverse#32]
원래 3글자 이상에서 최근 2글자만 입력해도 CREATE가 생성되었는데
다시 3글자 이상으로 변경됨 
1글자 이상으로 바꿀수 없는지 확인부탁드립니다

**Comment by yadorann** [comment]
확인하고 1글자 이상으로 반영하겟슴니다

**Comment by JOOHYUN85** [comment]
이것도 수정된 상태인가요? 여전히 3글자이상이어야 입력이 되서 반영된건지 확인부탁드립니다

**Comment by yadorann** [comment]
아 넵 한글자는 지금 반영해놓은 상태고 추가해놓으신 부분은 한 번 확인해보겟습니다

**Comment by JOOHYUN85** [comment]
넵 이건 해결되었습니다 감사합니다.
