### ISSUE TITLE
[급] 어드민 투표관리메뉴 편집버튼 버그

### ISSUE THREAD

**Issue by JOOHYUN85** [mossland/mossverse#33]
어드민 MOCSURVEY 메뉴 편집 버튼을 누르면 투표소 버그 메시지와 똑같이 뜨고 반응 하지 않음

![image](https://github.com/mossland/mossverse/assets/128334516/5acf5893-da17-4181-ada9-3555bc669efb)

**Comment by yadorann** [comment]
수정 후 메인넷에 반영했습니다!

**Comment by JOOHYUN85** [comment]
감사합니다!
