### ISSUE TITLE
안건 20개밖에 안보임

### ISSUE THREAD

**Issue by JOOHYUN85** [mossland/mossverse#34]
버그 수정되고 나서 안건이 20개까지밖에 안보여집니다
첫 안건까지 다 나오도록 부탁드립니다

![image](https://github.com/mossland/mossverse/assets/128334516/f059df2b-7e12-4894-964c-1d0a84a4a0a6)

**Comment by yadorann** [comment]
이번에 새로 기능을 개선해서 스크롤을 내리면 새로 추가로 나오게끔 세팅되어있습니다!

**Comment by JOOHYUN85** [comment]
스크롤을 내려도 예전 안건은 안보이는데요 딱 최근 20개까지만 보입니다

**Comment by yadorann** [comment]
음 맥북이랑 윈도우 둘 다 테스트 해봤는데 정상작동하는데 혹시 녹화가 가능할까요? 어떤 특별한 케이스가 있는 건지 확인해보려 합니다
일단 x스크롤 버그는 제거했습니다

**Comment by JOOHYUN85** [comment]
처음 투표소를 들어가면 여전히 스크롤을 해도 20개만 보이구요 (스크롤이 줄어들지않음)
화면을 축소하거나 확대하면 말씀하신대로 스크롤이 줄어들면서 모든 리스트가 보입니다. 
창을 끄고 나갔다가 다시 들어오면 다시 20개만 보이는 현상이 나타납니다


https://github.com/mossland/mossverse/assets/128334516/29e69d26-340e-4d0e-9c7d-86ba3a42561c

**Comment by yadorann** [comment]
예상되는 부분 수정하고 제 PC에서는 정상작동 확인했습니다 한 번 테스트 부탁드립니다!

**Comment by JOOHYUN85** [comment]
저는 계속 똑같은 현상이 발생합니다. 

1. 처음들어가면 스크롤 변화없이 20개까지만 보임
2. 화면비율을 축소하면 스크롤이 줄어들어 안건이 다 나타나고 확대하면 그대로 다 잘 보임
3. 창을 닫고 나갔다가 다시 들어오면 다시 스크롤변화없이 20개만 보임


https://github.com/mossland/mossverse/assets/128334516/ddaf8d4e-2221-409f-adea-4857adb8ecb6



https://github.com/mossland/mossverse/assets/128334516/5b657537-423e-40a4-8cc8-48763f454a91

**Comment by yadorann** [comment]
1, 2 번은 확인해보겟습니다

3번은 창을 닫으면 페이지를 나가는 개념이어서 처음부터 다시 스크롤 변화없이 20개부터 보이는 게 정상적인 작동 방법입니다

**Comment by yadorann** [comment]
소수점 관련해서 이슈가 있어서 수정했는데 다시 한 번 확인 부탁드리겟슴니다

**Comment by JOOHYUN85** [comment]
처음들어가면 스크롤바가 커서 안된것 같았는데 
밑으로 내릴수록 스크롤바가 줄어들어서 이제 다 보입니다.
감사합니다.

 

https://github.com/mossland/mossverse/assets/128334516/933f703b-1c95-4d52-9926-443ca482f9ca
