### ISSUE TITLE
[개선사항] 기간 종료된 안건 기간 늘릴 수 있는지 ★★★★☆

### ISSUE THREAD

**Issue by JOOHYUN85** [mossland/mossverse#35]
초반에 올렸던 안건들이 날짜가 종료되어 비활성화로 전환된 것들이 많은데 
어드민에 투표기간 부분을 넣고 여기서 날짜 조정해서 기간을 늘릴 수 있었으면 합니다. 

![image](https://github.com/mossland/mossverse/assets/128334516/320c27c0-1a7c-4249-9ea9-92c9413839cb)

**Comment by yadorann** [comment]
종료 날짜 기준으로 스냅샷을 찍어버려서 이 부분은 반영하기 좀 어려울 듯 합니다...

**Comment by JOOHYUN85** [comment]
네 알겠습니다!
